FILE=config.toml
if test -f "$FILE"; then
    sed -i "s/GITALK_CLIENT_ID_PLACEHOLDER/${GITALK_CLIENT_ID_PLACEHOLDER}/g" "$FILE"
    sed -i "s/GITALK_CLIENT_SECRET_PLACEHOLDER/${GITALK_CLIENT_SECRET_PLACEHOLDER}/g" "$FILE"
fi
